[project]
name = "is-odd-rs-exmaple"
version = "1.0.0"
authors = [
    {name = "작성자", email = "email@example.com"}
]
requires-python = ">=3.13"

dependencies = [
    "is-odd-rs"
]

[tool.uv.sources]
is-odd-rs = { workspace = true }
