[workspace]
members = [
    "libs/*",
]

resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["owjs3"]
description = "A Rust library to check if a number is odd"
license = "MIT"
repository = "https://github.com/owjs3/is-odd-rs"

[profile.release]
opt-level = "s" 